### ISSUE TITLE
Consider new APIs to feed dependencies directly in build.rs

### ISSUE THREAD

**Issue by nox** [joshtriplett/metadeps#5]
I've thought a bit more about the `toml` bump and realised something: what's even the point of specifying the third-party dependencies in Cargo.toml? That crate should just expose APIs to specify the list of dependencies as code in build.rs directly.

E.g. instead of writing:

```toml
[package.metadata.pkg-config]
testlib = "1.2"
testdata = { version = "4.5", feature = "use-testdata" }
```

One should just do:

```rust
extern crate metadeps;

use metadeps::pkg_config;

fn main() {
    pkg_config("testlib", "1.2", None);
    pkg_config("testdata", "4.5", Some("use-testdata"));
}
```

This way one does not need any parser, and it's not like specifying them in a declarative way in Cargo.toml brings much to the table anyway.
